### ISSUE TITLE
Need Help!

### ISSUE THREAD

**Issue by showoi** [ZeroM3m0ry/WDropper#2]
A little more info could be awesome! I compiled the project but yet still couldn't figure how to use it. Can you explain how to use it/or which parameters i need in command prompt to make it work?

**Comment by ZeroM3m0ry** [comment]
if you compiled it an executable file will generated in the same folder ,if you're using Visual Studio IDE you will find the executable file in this path `C:\Users\user\source\repos\WDropper\Debug` or `CTRL + F5` to run it  .
